spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/cidadaobot}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true

logging.level.br.com.othiagob.cidadaobot=DEBUG
logging.level.org.hibernate.SQL=DEBUG
server.port=8081

#REDIS / CACHE
spring.cache.type=redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

#AJUDA A VISUALIZAR COMPORTAMENTO DE CACHE DURANTE DESENVOLVIMENTO
loggin.level.org.springframeworking.cache=DEBUG
