spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true

spring.jpa.open-in-view=false

logging.level.root=INFO
logging.level.br.com.othiagob.cidadaobot=INFO
logging.level.org.hibernate.SQL=OFF
